const words = [
  {
    id: 0,
    word: "resemble",
    meaning: "v.像；与……相似",
    synonym: ["like", "look like", "be similar to"],
    level: "1",
  },
  {
    id: 1,
    word: "recognize",
    meaning: "v.认出；识别；承认",
    synonym: [
      "perceive",
      "acknowledge",
      "realize",
      "appreciate",
      "admit",
      "identify",
      "comprehend",
      "understand",
      "know",
    ],
    level: "1",
  },
  {
    id: 2,
    word: "adjust",
    meaning: "v.调整；使适合",
    synonym: ["change", "modify", "shift", "alter"],
    level: "1",
  },
  {
    id: 3,
    word: "approach",
    meaning: "n.方法",
    synonym: ["method", "way"],
    level: "1",
  },
  {
    id: 4,
    word: "fundamental",
    meaning: "adj.基本的；基础的",
    synonym: ["rudimentary", "preliminary", "basic"],
    level: "1",
  },
  {
    id: 5,
    word: "rely on",
    meaning: "依靠；依赖",
    synonym: ["depend on"],
    level: "1",
  },
  {
    id: 6,
    word: "domestic",
    meaning: "adj.家庭的；国内的",
    synonym: ["home", "local", "national"],
    level: "1",
  },
  {
    id: 7,
    word: "measure",
    meaning: "v.测量",
    synonym: ["calculate", "assess", "evaluate"],
    level: "1",
  },
  {
    id: 8,
    word: "trait",
    meaning: "n.特性；特征",
    synonym: ["characteristic", "feature", "property"],
    level: "1",
  },
  {
    id: 9,
    word: "coin",
    meaning: "v.创造",
    synonym: ["first used", "invent"],
    level: "1",
  },
  {
    id: 10,
    word: "artificial",
    meaning: "adj.人造的，仿造的",
    synonym: ["synthetic", "man-made"],
    level: "1",
  },
  {
    id: 11,
    word: "prompt",
    meaning: "v.促进；激起",
    synonym: ["initiate", "immediately"],
    level: "1",
  },
  {
    id: 12,
    word: "exchange",
    meaning: "v.交换",
    synonym: ["share", "apply A to B"],
    level: "1",
  },
  {
    id: 13,
    word: "underlie",
    meaning: "v.成为.….基础",
    synonym: ["based on", "ground", "root"],
    level: "1",
  },
  {
    id: 14,
    word: "ignore",
    meaning: "v.忽视；不顾",
    synonym: ["neglect", "overlook", "underestimate"],
    level: "1",
  },
  {
    id: 15,
    word: "fertilizer",
    meaning: "n.化肥；肥料",
    synonym: ["chemical", "toxic", "unnatural"],
    level: "1",
  },
  {
    id: 16,
    word: "that",
    meaning: "pron.那；那个",
    synonym: ["this", "it", "they", "those", "these", "such"],
    level: "1",
  },
  {
    id: 17,
    word: "and",
    meaning: "conj.和；而且",
    synonym: [
      "or",
      "as well as",
      "both…and",
      "not only…but also",
      "other than",
      "in addition",
      "besides",
      "on the one hand…on the other hand…",
      "neither…nor…",
    ],
    level: "1",
  },
  {
    id: 18,
    word: "rather than",
    meaning: "而非；不是",
    synonym: [
      "but",
      "yet",
      "however",
      "whereas",
      "nonetheless",
      "nevertheless",
      "notwithstanding",
      "although",
      "though",
      "instead",
    ],
    level: "1",
  },
  {
    id: 19,
    word: "thanks to",
    meaning: "由于；幸亏",
    synonym: [
      "stem from",
      "derive",
      "owing to",
      "due to",
      "according to",
      "because of",
      "on account of",
      "as a result of",
      "leading to",
      "because",
      "since for",
      "in that",
      "as",
      "therefore",
      "hence",
    ],
    level: "1",
  },
  {
    id: 20,
    word: "diversity",
    meaning: "n.多样性；差异",
    synonym: ["variety", "difference"],
    level: "2",
  },
  {
    id: 21,
    word: "detect",
    meaning: "v.查明；发现",
    synonym: ["look for", "find", "seek", "search"],
    level: "2",
  },
  {
    id: 22,
    word: "isolate",
    meaning: "v.使隔离；使孤立",
    synonym: ["inaccessible"],
    level: "2",
  },
  {
    id: 23,
    word: "avoid",
    meaning: "v.避免",
    synonym: ["escape", "evitable"],
    level: "2",
  },
  {
    id: 24,
    word: "budget",
    meaning: "n.预算",
    synonym: ["fund", "financial"],
    level: "2",
  },
  {
    id: 25,
    word: "adapt to",
    meaning: "使适应",
    synonym: ["fit", "suit"],
    level: "2",
  },
  {
    id: 26,
    word: "alternative",
    meaning: "adj.供替代的；供选择的     n.替代品",
    synonym: ["subsitute"],
    level: "2",
  },
  {
    id: 27,
    word: "compensate",
    meaning: "v.补偿；赔偿",
    synonym: ["make up", "off set"],
    level: "2",
  },
  {
    id: 28,
    word: "component",
    meaning: "n.成分；要素",
    synonym: ["proportion"],
    level: "2",
  },
  {
    id: 29,
    word: "military",
    meaning: "adj.军事的",
    synonym: ["weapon", "army"],
    level: "2",
  },
  {
    id: 30,
    word: "criteria",
    meaning: "n.标准",
    synonym: ["standard"],
    level: "2",
  },
  {
    id: 31,
    word: "curriculum",
    meaning: "n.课程",
    synonym: ["syllabus", "course of study"],
    level: "2",
  },
  {
    id: 32,
    word: "feasible",
    meaning: "adj.可行的",
    synonym: ["viable", "realistic"],
    level: "2",
  },
  {
    id: 33,
    word: "constrain",
    meaning: "v.束缚；限制",
    synonym: ["stop", "control"],
    level: "2",
  },
  {
    id: 34,
    word: "deficiency",
    meaning: "n.缺陷；缺点",
    synonym: ["shortage", "defect", "weakness"],
    level: "2",
  },
  {
    id: 35,
    word: "supplement",
    meaning: "v.补充",
    synonym: ["provision"],
    level: "2",
  },
  {
    id: 36,
    word: "distinguish",
    meaning: "v.区别；辨别",
    synonym: ["separete", "differentiate"],
    level: "2",
  },
  {
    id: 37,
    word: "analyze",
    meaning: "v.分析；解释",
    synonym: ["examine", "diagnose"],
    level: "2",
  },
  {
    id: 38,
    word: "empharsize",
    meaning: "v.强调；着重",
    synonym: ["focus on", "stress"],
    level: "2",
  },
  {
    id: 39,
    word: "enormous",
    meaning: "adj.庞大的；巨大的",
    synonym: ["massive", "large"],
    level: "2",
  },
  {
    id: 40,
    word: "imitate",
    meaning: "v.模仿",
    synonym: ["mimic", "copy"],
    level: "2",
  },
  {
    id: 41,
    word: "impair",
    meaning: "v.削弱；减少",
    synonym: ["damage", "diminish", "decrease"],
    level: "2",
  },
  {
    id: 42,
    word: "hinder",
    meaning: "v.阻碍",
    synonym: ["impede", "prevent", "deter", "obstacle"],
    level: "2",
  },
  {
    id: 43,
    word: "legitimate",
    meaning: "adj.合法的",
    synonym: ["legal"],
    level: "2",
  },
  {
    id: 44,
    word: "limitation",
    meaning: "n.限制",
    synonym: ["restriction"],
    level: "2",
  },
  {
    id: 45,
    word: "convention",
    meaning: "n.手法；习俗",
    synonym: ["method", "traditon"],
    level: "2",
  },
  {
    id: 46,
    word: "demanding",
    meaning: "adj.苛求的",
    synonym: ["troublesome"],
    level: "2",
  },
  {
    id: 47,
    word: "determine",
    meaning: "v.决定",
    synonym: ["decide"],
    level: "2",
  },
  {
    id: 48,
    word: "accelerate",
    meaning: "v.加速；促进；强调",
    synonym: ["speed up"],
    level: "2",
  },
  {
    id: 49,
    word: "ancient",
    meaning: "adj.古代的；古老的",
    synonym: ["aged", "old"],
    level: "2",
  },
  {
    id: 50,
    word: "beneficial",
    meaning: "adj.有益的",
    synonym: ["helpful", "advantageous", "wholesome"],
    level: "2",
  },
  {
    id: 51,
    word: "chronic",
    meaning: "adj.慢性的；长期性的",
    synonym: ["lasting"],
    level: "2",
  },
  {
    id: 52,
    word: "conscious",
    meaning: "adj.有意识的；神志清醒的",
    synonym: ["aware", "knowing"],
    level: "2",
  },
  {
    id: 53,
    word: "minimize",
    meaning: "v.最小化；使……减到最小",
    synonym: ["reduce", "lessen"],
    level: "2",
  },
  {
    id: 54,
    word: "immunity",
    meaning: "n.免疫力",
    synonym: ["resistance"],
    level: "2",
  },
  {
    id: 55,
    word: "imperactive",
    meaning: "adj.必要的；紧急的",
    synonym: ["compelling", "necessary", "urgent"],
    level: "2",
  },
  {
    id: 56,
    word: "secrete",
    meaning: "v.分泌",
    synonym: ["discharge", "exude"],
    level: "2",
  },
  {
    id: 57,
    word: "exaggerate",
    meaning: "v.夸大；夸张",
    synonym: ["overstate"],
    level: "2",
  },
  {
    id: 58,
    word: "transmit",
    meaning: "v.传达；传输",
    synonym: ["pass", "send", "transfer"],
    level: "2",
  },
  {
    id: 59,
    word: "extinct",
    meaning: "v.灭绝",
    synonym: ["die out", "lost"],
    level: "2",
  },
  {
    id: 60,
    word: "exclusive",
    meaning: "adj.独有的；排外的；专一的",
    synonym: ["only"],
    level: "2",
  },
  {
    id: 61,
    word: "guarantee",
    meaning: "v.保证；担保",
    synonym: ["assure"],
    level: "2",
  },
  {
    id: 62,
    word: "inherit",
    meaning: "v.继承",
    synonym: ["receive"],
    level: "2",
  },
  {
    id: 63,
    word: "witness",
    meaning: "n.见证；证据；目击者",
    synonym: ["view", "see"],
    level: "2",
  },
  {
    id: 64,
    word: "magnetic",
    meaning: "adj.有磁性的",
    synonym: ["attractive"],
    level: "2",
  },
  {
    id: 65,
    word: "loss",
    meaning: "n.减少；亏损；失败；遗失",
    synonym: ["waste", "gone"],
    level: "2",
  },
  {
    id: 66,
    word: "option",
    meaning: "n.选择",
    synonym: ["choice"],
    level: "2",
  },
  {
    id: 67,
    word: "prefer to",
    meaning: "更喜欢",
    synonym: ["rather"],
    level: "2",
  },
  {
    id: 68,
    word: "priority",
    meaning: "n.优先权",
    synonym: ["preference", "preferential"],
    level: "2",
  },
  {
    id: 69,
    word: "primary",
    meaning: "adj.主要的",
    synonym: ["principal", "main"],
    level: "2",
  },
  {
    id: 70,
    word: "principle",
    meaning: "n.原理",
    synonym: ["rule"],
    level: "2",
  },
  {
    id: 71,
    word: "potential",
    meaning: "n.潜能adj.潜在的",
    synonym: ["possibility"],
    level: "2",
  },
  {
    id: 72,
    word: "quantity",
    meaning: "n.量；数量",
    synonym: ["number"],
    level: "2",
  },
  {
    id: 73,
    word: "settle",
    meaning: "v.解决；定居；稳定",
    synonym: ["fix", "figure out"],
    level: "2",
  },
  {
    id: 74,
    word: "sophistiate",
    meaning: "v.使复杂",
    synonym: ["complicate"],
    level: "2",
  },
  {
    id: 75,
    word: "specific",
    meaning: "adj.明确的；特殊的",
    synonym: ["detailed", "particular"],
    level: "2",
  },
  {
    id: 76,
    word: "survive",
    meaning: "v.存活；幸存",
    synonym: ["remain"],
    level: "2",
  },
  {
    id: 77,
    word: "swift",
    meaning: "adj.迅速的；敏捷的；立刻的",
    synonym: ["quick", "rapid"],
    level: "2",
  },
  {
    id: 78,
    word: "unexpectedly",
    meaning: "adv.出乎意料地",
    synonym: ["surprising"],
    level: "2",
  },
  {
    id: 79,
    word: "surrounding",
    meaning: "n.环境",
    synonym: ["setting", "environment"],
    level: "2",
  },
  {
    id: 80,
    word: "attempt",
    meaning: "v.试图；尝试",
    synonym: ["try", "test"],
    level: "2",
  },
  {
    id: 81,
    word: "expertise",
    meaning: "v.专门技术",
    synonym: ["knowledge", "skill"],
    level: "2",
  },
  {
    id: 82,
    word: "faculty",
    meaning: "n.能力；才能；全体教员",
    synonym: ["ability"],
    level: "2",
  },
  {
    id: 83,
    word: "donate",
    meaning: "v.捐赠",
    synonym: ["contribute"],
    level: "2",
  },
  {
    id: 84,
    word: "dynamics",
    meaning: "n.动力学",
    synonym: ["energy", "force", "move"],
    level: "2",
  },
  {
    id: 85,
    word: "incentive",
    meaning: "n.刺激；鼓励；动机",
    synonym: ["motive", "stimulus"],
    level: "2",
  },
  {
    id: 86,
    word: "mortality",
    meaning: "n.死亡率",
    synonym: ["death"],
    level: "2",
  },
  {
    id: 87,
    word: "peripheral",
    meaning: "adj.喊外围的；次要的",
    synonym: ["unimportant", "minor"],
    level: "2",
  },
  {
    id: 88,
    word: "vicinity",
    meaning: "n.邻近；附近",
    synonym: ["neighbourhood", "nearby"],
    level: "2",
  },
  {
    id: 89,
    word: "threaten",
    meaning: "v.威胁；危及",
    synonym: ["endanger", "jeopardize", "risk", "hazard"],
    level: "2",
  },
  {
    id: 90,
    word: "practice",
    meaning: "n.实行；练习",
    synonym: ["method", "exercise"],
    level: "2",
  },
  {
    id: 91,
    word: "bacteria",
    meaning: "n.细菌",
    synonym: ["virus", "germ", "microbe"],
    level: "2",
  },
  {
    id: 92,
    word: "be subject to",
    meaning: "受……支配",
    synonym: ["face"],
    level: "2",
  },
  {
    id: 93,
    word: "be liable to",
    meaning: "易于……",
    synonym: ["portential"],
    level: "2",
  },
  {
    id: 94,
    word: "innate",
    meaning: "adj.天生的；内在的；直觉的",
    synonym: ["built-in", "inborn"],
    level: "2",
  },
  {
    id: 95,
    word: "pattern",
    meaning: "n.模式",
    synonym: ["formation"],
    level: "2",
  },
  {
    id: 96,
    word: "therapy",
    meaning: "n.治疗；理疗",
    synonym: ["treatment"],
    level: "2",
  },
  {
    id: 97,
    word: "original",
    meaning: "adj.原始的；最初的",
    synonym: ["initial", "first"],
    level: "2",
  },
  {
    id: 98,
    word: "confidential",
    meaning: "adj.机密的；秘密的",
    synonym: ["undiscovered", "secret", "hidden"],
    level: "2",
  },
  {
    id: 99,
    word: "cognitive",
    meaning: "adj.认知的",
    synonym: ["mental"],
    level: "2",
  },
  {
    id: 100,
    word: "comply with",
    meaning: "照做；遵守",
    synonym: ["obey"],
    level: "2",
  },
  {
    id: 101,
    word: "consult",
    meaning: "v.查阅；商量；请教；咨询",
    synonym: ["ask for advice"],
    level: "2",
  },
  {
    id: 102,
    word: "superior",
    meaning: "adj.上级的；优秀的",
    synonym: ["higher", "upper"],
    level: "2",
  },
  {
    id: 103,
    word: "co-operation",
    meaning: "n.合作；协作",
    synonym: ["support", "work together"],
    level: "2",
  },
  {
    id: 104,
    word: "co-ordinate",
    meaning: "v.使…….协调",
    synonym: ["organize", "harmonize"],
    level: "2",
  },
  {
    id: 105,
    word: "differ",
    meaning: "v.使……相异；使….不同",
    synonym: ["vary"],
    level: "2",
  },
  {
    id: 106,
    word: "cue",
    meaning: "n.线索",
    synonym: ["hint", "clue"],
    level: "2",
  },
  {
    id: 107,
    word: "signal",
    meaning: "n.信号",
    synonym: ["symbol", "mark", "sign"],
    level: "2",
  },
  {
    id: 108,
    word: "abandon",
    meaning: "v.放弃；遗弃",
    synonym: ["quit", "give up", "forsake", "derelict"],
    level: "2",
  },
  {
    id: 109,
    word: "halt",
    meaning: "n.停止",
    synonym: ["stop", "quit"],
    level: "2",
  },
  {
    id: 110,
    word: "fragile",
    meaning: "adj.脆弱的",
    synonym: ["vulnerable"],
    level: "2",
  },
  {
    id: 111,
    word: "retain",
    meaning: "v.记住",
    synonym: ["maintain"],
    level: "2",
  },
  {
    id: 112,
    word: "vanish",
    meaning: "v.消失；绝迹",
    synonym: ["disappear"],
    level: "2",
  },
  {
    id: 113,
    word: "delivery",
    meaning: "n.递送",
    synonym: ["send"],
    level: "2",
  },
  {
    id: 114,
    word: "erode",
    meaning: "v.侵蚀",
    synonym: ["rust", "damage"],
    level: "2",
  },
  {
    id: 115,
    word: "induce",
    meaning: "v.引起；引诱",
    synonym: ["cause", "lead to"],
    level: "2",
  },
  {
    id: 116,
    word: "stable",
    meaning: "adj.稳定的",
    synonym: ["constant", "unchanged"],
    level: "2",
  },
  {
    id: 117,
    word: "integrate",
    meaning: "v.使……成整体",
    synonym: ["combine", "whole"],
    level: "2",
  },
  {
    id: 118,
    word: "equal",
    meaning: "adj.平等的；相等的；胜任的",
    synonym: ["fair", "even"],
    level: "2",
  },
  {
    id: 119,
    word: "grant",
    meaning: "v.拨款；授予",
    synonym: ["offer"],
    level: "2",
  },
  {
    id: 120,
    word: "accumulate",
    meaning: "v.累积；积聚",
    synonym: ["gather"],
    level: "3",
  },
  {
    id: 121,
    word: "addictive",
    meaning: "adj.上瘾的",
    synonym: ["habit"],
    level: "3",
  },
  {
    id: 122,
    word: "adversity",
    meaning: "n.逆境；不幸",
    synonym: ["trouble"],
    level: "3",
  },
  {
    id: 123,
    word: "aggression",
    meaning: "v.侵犯；侵害",
    synonym: ["attack"],
    level: "3",
  },
  {
    id: 124,
    word: "agreeable",
    meaning: "adj.令人愉快的；适合的；和蔼可亲的",
    synonym: ["pleasant"],
    level: "3",
  },
  {
    id: 125,
    word: "aid",
    meaning: "n.援助；帮助",
    synonym: ["help"],
    level: "3",
  },
  {
    id: 126,
    word: "allergic",
    meaning: "adj.过敏的；对……极讨厌的",
    synonym: ["irritate"],
    level: "3",
  },
  {
    id: 127,
    word: "altitude",
    meaning: "n.高度；海拔",
    synonym: ["height"],
    level: "3",
  },
  {
    id: 128,
    word: "application",
    meaning: "n.应用",
    synonym: ["utilization"],
    level: "3",
  },
  {
    id: 129,
    word: "approve",
    meaning: "v.批准",
    synonym: ["agree"],
    level: "3",
  },
  {
    id: 130,
    word: "array",
    meaning: "n.排列；大批",
    synonym: ["order"],
    level: "3",
  },
  {
    id: 131,
    word: "assign",
    meaning: "v.分配；指派",
    synonym: ["allocate"],
    level: "3",
  },
  {
    id: 132,
    word: "association",
    meaning: "n.协会；联盟；联系",
    synonym: ["union"],
    level: "3",
  },
  {
    id: 133,
    word: "attitude",
    meaning: "n.看法；态度",
    synonym: ["opinion"],
    level: "3",
  },
  {
    id: 134,
    word: "authority",
    meaning: "n.当局；权威",
    synonym: ["government"],
    level: "3",
  },
  {
    id: 135,
    word: "be consistent with",
    meaning: "与…….致",
    synonym: ["compatible"],
    level: "3",
  },
  {
    id: 136,
    word: "bear",
    meaning: "v.承担；忍受",
    synonym: ["tolerate"],
    level: "3",
  },
  {
    id: 137,
    word: "blight",
    meaning: "v.损害；枯萎",
    synonym: ["destroy"],
    level: "3",
  },
  {
    id: 138,
    word: "boundary",
    meaning: "n.边界；底线",
    synonym: ["barrier"],
    level: "3",
  },
  {
    id: 139,
    word: "bungle",
    meaning: "v.搞糟；拙劣地工作",
    synonym: ["mishandle"],
    level: "3",
  },
  { id: 140, word: "burden", meaning: "n.负担", synonym: ["load"], level: "3" },
  {
    id: 141,
    word: "calamity",
    meaning: "n.灾难",
    synonym: ["disaster"],
    level: "3",
  },
  {
    id: 142,
    word: "capacity",
    meaning: "n.容量",
    synonym: ["volume"],
    level: "3",
  },
  {
    id: 143,
    word: "catastrophic",
    meaning: "adj.灾难的",
    synonym: ["disastrous"],
    level: "3",
  },
  {
    id: 144,
    word: "cater",
    meaning: "v.迎合；满足需要",
    synonym: ["serve"],
    level: "3",
  },
  {
    id: 145,
    word: "certify",
    meaning: "v.证明；保证",
    synonym: ["verify"],
    level: "3",
  },
  {
    id: 146,
    word: "civic",
    meaning: "adj.市民的",
    synonym: ["municipal"],
    level: "3",
  },
  {
    id: 147,
    word: "comment",
    meaning: "n.评论；意见 v.评论",
    synonym: ["remark"],
    level: "3",
  },
  {
    id: 148,
    word: "commiment",
    meaning: "n.承诺；许诺；义务；致力",
    synonym: ["engagement"],
    level: "3",
  },
  {
    id: 149,
    word: "communal",
    meaning: "adj.公共的；公社的",
    synonym: ["public"],
    level: "3",
  },
  {
    id: 150,
    word: "commute",
    meaning: "v.通勤；用.….交换",
    synonym: ["travel"],
    level: "3",
  },
  {
    id: 151,
    word: "compare",
    meaning: "v.与….相比较",
    synonym: ["contrast"],
    level: "3",
  },
  {
    id: 152,
    word: "conceal",
    meaning: "v.隐藏；隐瞒",
    synonym: ["hide"],
    level: "3",
  },
  {
    id: 153,
    word: "concentrate",
    meaning: "v.专心于；集中",
    synonym: ["focus"],
    level: "3",
  },
  {
    id: 154,
    word: "concur",
    meaning: "v.同意",
    synonym: ["agree"],
    level: "3",
  },
  {
    id: 155,
    word: "confer",
    meaning: "v.授予；给予",
    synonym: ["grant"],
    level: "3",
  },
  {
    id: 156,
    word: "conflict",
    meaning: "n.冲突；矛盾",
    synonym: ["unharmonious"],
    level: "3",
  },
  {
    id: 157,
    word: "confuse",
    meaning: "v.使混乱；使迷惑",
    synonym: ["puzzle"],
    level: "3",
  },
  {
    id: 158,
    word: "conservative",
    meaning: "adj.保守的",
    synonym: ["traditional"],
    level: "3",
  },
  {
    id: 159,
    word: "considerable",
    meaning: "adj相当大的；重要的",
    synonym: ["significant"],
    level: "3",
  },
  {
    id: 160,
    word: "contingent",
    meaning: "adj.因情况而异的",
    synonym: ["uncertain"],
    level: "3",
  },
  {
    id: 161,
    word: "controversial",
    meaning: "adj.有争论的",
    synonym: ["disputable"],
    level: "3",
  },
  {
    id: 162,
    word: "correlation",
    meaning: "n.相关；关联",
    synonym: ["link"],
    level: "3",
  },
  {
    id: 163,
    word: "courtship",
    meaning: "n.求爱（时期）",
    synonym: ["mate"],
    level: "3",
  },
  {
    id: 164,
    word: "crash",
    meaning: "n.碰撞",
    synonym: ["collapse"],
    level: "3",
  },
  {
    id: 165,
    word: "credibility",
    meaning: "n.可信性",
    synonym: ["reliance"],
    level: "3",
  },
  {
    id: 166,
    word: "criminal",
    meaning: "n.罪犯；犯人",
    synonym: ["conviction"],
    level: "3",
  },
  {
    id: 167,
    word: "crisis",
    meaning: "n.危机",
    synonym: ["risk"],
    level: "3",
  },
  {
    id: 168,
    word: "criticism",
    meaning: "n.批评",
    synonym: ["condemn"],
    level: "3",
  },
  {
    id: 169,
    word: "curb",
    meaning: "v.限制、抑制",
    synonym: ["restrict"],
    level: "3",
  },
  {
    id: 170,
    word: "damp",
    meaning: "adj.潮湿的",
    synonym: ["wet"],
    level: "3",
  },
  {
    id: 171,
    word: "dazzle",
    meaning: "v.使目眩；使……眼花",
    synonym: ["flash"],
    level: "3",
  },
  {
    id: 172,
    word: "deadline",
    meaning: "n.最后期限",
    synonym: ["limit"],
    level: "3",
  },
  {
    id: 173,
    word: "delay",
    meaning: "n.延期；耽搁",
    synonym: ["postpone"],
    level: "3",
  },
  {
    id: 174,
    word: "democratic",
    meaning: "adj.民主的",
    synonym: ["republic"],
    level: "3",
  },
  {
    id: 175,
    word: "demographic",
    meaning: "adj.人口统计学的；人口学的",
    synonym: ["populaiton statistic"],
    level: "3",
  },
  {
    id: 176,
    word: "dental",
    meaning: "adj.牙科的，牙齿的",
    synonym: ["teeth"],
    level: "3",
  },
  {
    id: 177,
    word: "depression",
    meaning: "n.抑郁；沮丧",
    synonym: ["frustration"],
    level: "3",
  },
  {
    id: 178,
    word: "designate",
    meaning: "v.指定；指派；标出",
    synonym: ["appoint"],
    level: "3",
  },
  { id: 179, word: "detain", meaning: "v.留住", synonym: ["hold"], level: "3" },
  {
    id: 180,
    word: "devastate",
    meaning: "v.毁坏；毁灭",
    synonym: ["wreck"],
    level: "3",
  },
  {
    id: 181,
    word: "disclose",
    meaning: "v.公开；揭露",
    synonym: ["expose"],
    level: "3",
  },
  {
    id: 182,
    word: "disparate",
    meaning: "adj.不同的",
    synonym: ["different"],
    level: "3",
  },
  {
    id: 183,
    word: "display",
    meaning: "v.显示",
    synonym: ["show"],
    level: "3",
  },
  {
    id: 184,
    word: "disrupt",
    meaning: "v.破坏",
    synonym: ["distroy"],
    level: "3",
  },
  {
    id: 185,
    word: "distract",
    meaning: "v.转移；分心",
    synonym: ["divert"],
    level: "3",
  },
  {
    id: 186,
    word: "distribute",
    meaning: "v.分配；分发",
    synonym: ["spread"],
    level: "3",
  },
  {
    id: 187,
    word: "documention",
    meaning: "n.文件；文献",
    synonym: ["record"],
    level: "3",
  },
  {
    id: 188,
    word: "domain",
    meaning: "n.领域",
    synonym: ["field"],
    level: "3",
  },
  {
    id: 189,
    word: "dominate",
    meaning: "adj.占优势的；占支配地位的",
    synonym: ["overbearing"],
    level: "3",
  },
  {
    id: 190,
    word: "dramatic",
    meaning: "adj.戏剧化的；激动人心的；引人注意的",
    synonym: ["striking"],
    level: "3",
  },
  { id: 191, word: "drought", meaning: "n.干旱", synonym: ["dry"], level: "3" },
  {
    id: 192,
    word: "durable",
    meaning: "adj.持久的",
    synonym: ["lasting"],
    level: "3",
  },
  {
    id: 193,
    word: "eco-friendly",
    meaning: "adj.生态友好的，环保的",
    synonym: ["environmentally-friendly"],
    level: "3",
  },
  {
    id: 194,
    word: "elaborate",
    meaning: "v.详细阐述；详细叙述",
    synonym: ["illustrate"],
    level: "3",
  },
  {
    id: 195,
    word: "elderly",
    meaning: "adj. 高龄的",
    synonym: ["aged"],
    level: "3",
  },
  {
    id: 196,
    word: "eliminate",
    meaning: "v.消除；排除",
    synonym: ["dispose"],
    level: "3",
  },
  {
    id: 197,
    word: "elusive",
    meaning: "adj.难懂的；难捉摸的；行踪隐秘的",
    synonym: ["hard"],
    level: "3",
  },
  {
    id: 198,
    word: "encyclopedia",
    meaning: "n.百科全书",
    synonym: ["entire range of knowledge"],
    level: "3",
  },
  {
    id: 199,
    word: "entrepreneur",
    meaning: "n.企业家",
    synonym: ["boss"],
    level: "3",
  },
  {
    id: 200,
    word: "equator",
    meaning: "n.赤道",
    synonym: ["geography"],
    level: "3",
  },
  {
    id: 201,
    word: "erratically",
    meaning: "adv.不定地；无规律的",
    synonym: ["unpredictably"],
    level: "3",
  },
  {
    id: 202,
    word: "established",
    meaning: "adj.确定的；已制定的；已建立的",
    synonym: ["built"],
    level: "3",
  },
  {
    id: 203,
    word: "estate",
    meaning: "n.房地产",
    synonym: ["property"],
    level: "3",
  },
  {
    id: 204,
    word: "ethical",
    meaning: "adj.道德的",
    synonym: ["moral"],
    level: "3",
  },
  {
    id: 205,
    word: "eventually",
    meaning: "adv.最后；终于",
    synonym: ["finally"],
    level: "3",
  },
  {
    id: 206,
    word: "evidence",
    meaning: "n.迹象；证据",
    synonym: ["proof"],
    level: "3",
  },
  {
    id: 207,
    word: "evolve",
    meaning: "v.进化；发展；逐渐形成",
    synonym: ["develop"],
    level: "3",
  },
  {
    id: 208,
    word: "exceptional",
    meaning: "adj.异常的；特别出色的",
    synonym: ["extreme", "utmost"],
    level: "3",
  },
  {
    id: 209,
    word: "exhausted",
    meaning: "adj.疲惫的；耗尽的",
    synonym: ["fatigue"],
    level: "3",
  },
  {
    id: 210,
    word: "experiment",
    meaning: "n.实验；试验",
    synonym: ["test"],
    level: "3",
  },
  {
    id: 211,
    word: "explicit",
    meaning: "adj. 明确的",
    synonym: ["clear"],
    level: "3",
  },
  {
    id: 212,
    word: "exploit",
    meaning: "v.开发；利用",
    synonym: ["use"],
    level: "3",
  },
  {
    id: 213,
    word: "extend",
    meaning: "v.扩展；延伸；推广",
    synonym: ["expand"],
    level: "3",
  },
  {
    id: 214,
    word: "extract",
    meaning: "v.提取",
    synonym: ["quotaition"],
    level: "3",
  },
  {
    id: 215,
    word: "famine",
    meaning: "n.饥荒",
    synonym: ["hunger"],
    level: "3",
  },
  {
    id: 216,
    word: "finite",
    meaning: "adj.有限的",
    synonym: ["limited"],
    level: "3",
  },
  {
    id: 217,
    word: "fitness",
    meaning: "n.健康",
    synonym: ["heath"],
    level: "3",
  },
  {
    id: 218,
    word: "foe",
    meaning: "n.敌人，危害物",
    synonym: ["enemy"],
    level: "3",
  },
  {
    id: 219,
    word: "format",
    meaning: "n.格式",
    synonym: ["structure"],
    level: "3",
  },
  {
    id: 220,
    word: "fragment",
    meaning: "n.碎片",
    synonym: ["piece"],
    level: "3",
  },
  {
    id: 221,
    word: "freeze",
    meaning: "n.冰冻；冻结",
    synonym: ["chill"],
    level: "3",
  },
  {
    id: 222,
    word: "fullfill",
    meaning: "v.满足；实现",
    synonym: ["execute"],
    level: "3",
  },
  { id: 223, word: "gene", meaning: "n.基因", synonym: ["factor"], level: "3" },
  {
    id: 224,
    word: "gifted",
    meaning: "adj.有天赋的；有才华的",
    synonym: ["talented"],
    level: "3",
  },
  {
    id: 225,
    word: "graphic",
    meaning: "adj.形象的；图解的",
    synonym: ["picture"],
    level: "3",
  },
  {
    id: 226,
    word: "habitat",
    meaning: "n.栖息地；住处",
    synonym: ["residence"],
    level: "3",
  },
  {
    id: 227,
    word: "harbour",
    meaning: "v.怀有 n.海港",
    synonym: ["hold"],
    level: "3",
  },
  {
    id: 228,
    word: "hardship",
    meaning: "n.困苦；苦难",
    synonym: ["difficult"],
    level: "3",
  },
  {
    id: 229,
    word: "harsh",
    meaning: "adj.办艰难的；严酷的",
    synonym: ["rough"],
    level: "3",
  },
  {
    id: 230,
    word: "hypothesis",
    meaning: "n.假设",
    synonym: ["assumption"],
    level: "3",
  },
  {
    id: 231,
    word: "impact",
    meaning: "n.影响",
    synonym: ["influence"],
    level: "3",
  },
  {
    id: 232,
    word: "impressive",
    meaning: "adj.感人的；给人深刻印象的",
    synonym: ["touching"],
    level: "3",
  },
  {
    id: 233,
    word: "in accordance with",
    meaning: "依照",
    synonym: ["conform"],
    level: "3",
  },
  {
    id: 234,
    word: "inaccurate",
    meaning: "adj.错误的",
    synonym: ["incorrect"],
    level: "3",
  },
  {
    id: 235,
    word: "inactive",
    meaning: "adj.不活跃的，不活动的",
    synonym: ["passive"],
    level: "3",
  },
  {
    id: 236,
    word: "inappropriate",
    meaning: "adj.不适当的",
    synonym: ["hard"],
    level: "3",
  },
  {
    id: 237,
    word: "indulge",
    meaning: "v.沉溺（于）",
    synonym: ["spoil"],
    level: "3",
  },
  {
    id: 238,
    word: "infest",
    meaning: "v.侵害；寄生于",
    synonym: ["plague"],
    level: "3",
  },
  {
    id: 239,
    word: "installment",
    meaning: "n.安装；分期付款",
    synonym: ["payment on its completion"],
    level: "3",
  },
  {
    id: 240,
    word: "intelligence",
    meaning: "n.智力",
    synonym: ["mind"],
    level: "3",
  },
  {
    id: 241,
    word: "intense",
    meaning: "adj.强烈的；紧张的；热情的",
    synonym: ["strong"],
    level: "3",
  },
  {
    id: 242,
    word: "interaction",
    meaning: "n.相互作用，交流互动",
    synonym: ["social activities"],
    level: "3",
  },
  {
    id: 243,
    word: "interference",
    meaning: "n.干涉",
    synonym: ["interdependence"],
    level: "3",
  },
  {
    id: 244,
    word: "interior",
    meaning: "n.内部 adj.内部的",
    synonym: ["inner"],
    level: "3",
  },
  {
    id: 245,
    word: "interrupt",
    meaning: "v.中断",
    synonym: ["stop"],
    level: "3",
  },
  {
    id: 246,
    word: "introverted",
    meaning: "adj.内向的；含蓄的",
    synonym: ["shyness"],
    level: "3",
  },
  {
    id: 247,
    word: "involve",
    meaning: "v.包含；牵涉",
    synonym: ["associate"],
    level: "3",
  },
  {
    id: 248,
    word: "keen",
    meaning: "adj.热切的；急迫的；强烈的",
    synonym: ["strong"],
    level: "3",
  },
  {
    id: 249,
    word: "label",
    meaning: "v.打上标签",
    synonym: ["display"],
    level: "3",
  },
  {
    id: 250,
    word: "lack",
    meaning: "v.缺乏；不足",
    synonym: ["shortage"],
    level: "3",
  },
  {
    id: 251,
    word: "landscape",
    meaning: "n.风景",
    synonym: ["scene"],
    level: "3",
  },
  {
    id: 252,
    word: "likelihood",
    meaning: "n.可能性",
    synonym: ["chance"],
    level: "3",
  },
  {
    id: 253,
    word: "limb",
    meaning: "n.四肢",
    synonym: ["arm or leg"],
    level: "3",
  },
  {
    id: 254,
    word: "linguistic",
    meaning: "adj.语言（学）的",
    synonym: ["language"],
    level: "3",
  },
  {
    id: 255,
    word: "log",
    meaning: "v.记录 n.原木",
    synonym: ["record"],
    level: "3",
  },
  {
    id: 256,
    word: "look-in",
    meaning: "n.成功的机会",
    synonym: ["opportunity", "chance"],
    level: "3",
  },
  {
    id: 257,
    word: "lopsided",
    meaning: "adj.不平衡的",
    synonym: ["uneven"],
    level: "3",
  },
  {
    id: 258,
    word: "mainly",
    meaning: "adv.主要地；大体上",
    synonym: ["primarily"],
    level: "3",
  },
  {
    id: 259,
    word: "malfunction",
    meaning: "v.发生故障；不起作用",
    synonym: ["breakdown"],
    level: "3",
  },
  {
    id: 260,
    word: "mammal",
    meaning: "n.哺乳动物",
    synonym: ["creature"],
    level: "3",
  },
  {
    id: 261,
    word: "manage to do",
    meaning: "设法完成某事",
    synonym: ["success"],
    level: "3",
  },
  {
    id: 262,
    word: "manifest",
    meaning: "v.出现；表现",
    synonym: ["obvious"],
    level: "3",
  },
  {
    id: 263,
    word: "manufacture",
    meaning: "n.生产",
    synonym: ["produce"],
    level: "3",
  },
  {
    id: 264,
    word: "marine",
    meaning: "adj.海产的；航海的；海运的",
    synonym: ["sea"],
    level: "3",
  },
  { id: 265, word: "mate", meaning: "n.配偶", synonym: ["spouse"], level: "3" },
  {
    id: 266,
    word: "mechanism",
    meaning: "n.机制；原理",
    synonym: ["method"],
    level: "3",
  },
  {
    id: 267,
    word: "mental",
    meaning: "adj.精神的；心理的",
    synonym: ["intelligent"],
    level: "3",
  },
  {
    id: 268,
    word: "mercury",
    meaning: "n.汞；水银",
    synonym: ["liquid metal"],
    level: "3",
  },
  {
    id: 269,
    word: "meteorology",
    meaning: "adj.气象学的",
    synonym: ["weather"],
    level: "3",
  },
  {
    id: 270,
    word: "migrate",
    meaning: "v.转移；迁移",
    synonym: ["move"],
    level: "3",
  },
  {
    id: 271,
    word: "moisture",
    meaning: "n.水分；湿度",
    synonym: ["humidity"],
    level: "3",
  },
  {
    id: 272,
    word: "monitor",
    meaning: "v.监控",
    synonym: ["surveillance"],
    level: "3",
  },
  {
    id: 273,
    word: "motif",
    meaning: "n.主题；图形",
    synonym: ["theme"],
    level: "3",
  },
  {
    id: 274,
    word: "mould",
    meaning: "v.模压；塑造；塑造成",
    synonym: ["form"],
    level: "3",
  },
  {
    id: 275,
    word: "native",
    meaning: "adj.本国的；土著的；天然的；天赋的",
    synonym: ["original"],
    level: "3",
  },
  {
    id: 276,
    word: "nocturnal",
    meaning: "adj.夜间的；夜间发生的",
    synonym: ["night"],
    level: "3",
  },
  {
    id: 277,
    word: "norm",
    meaning: "n.规范",
    synonym: ["regulation"],
    level: "3",
  },
  {
    id: 278,
    word: "notoriety",
    meaning: "n.名声",
    synonym: ["famous"],
    level: "3",
  },
  {
    id: 279,
    word: "objective",
    meaning: "n.目标 adj.客观的",
    synonym: ["goal"],
    level: "3",
  },
  {
    id: 280,
    word: "obligation",
    meaning: "n.义务",
    synonym: ["responsibility"],
    level: "3",
  },
  {
    id: 281,
    word: "obscure",
    meaning: "v.掩盖；使模糊不清",
    synonym: ["hide"],
    level: "3",
  },
  { id: 282, word: "obtain", meaning: "v.获得", synonym: ["get"], level: "3" },
  {
    id: 283,
    word: "odd",
    meaning: "adj.古怪的",
    synonym: ["strange"],
    level: "3",
  },
  { id: 284, word: "odour", meaning: "n.气味", synonym: ["smell"], level: "3" },
  {
    id: 285,
    word: "offensive",
    meaning: "adj.冒犯的；无礼的",
    synonym: ["hostile"],
    level: "3",
  },
  {
    id: 286,
    word: "official",
    meaning: "adj.官方的",
    synonym: ["authority"],
    level: "3",
  },
  {
    id: 287,
    word: "optimum",
    meaning: "n.最佳效果 adj.最适宜的",
    synonym: ["best"],
    level: "3",
  },
  {
    id: 288,
    word: "ordinary",
    meaning: "adj.普通的；平凡的；平常的",
    synonym: ["common"],
    level: "3",
  },
  {
    id: 289,
    word: "organ",
    meaning: "n.器官；机构",
    synonym: ["a part of body"],
    level: "3",
  },
  {
    id: 290,
    word: "out of question",
    meaning: "不可能",
    synonym: ["impossible"],
    level: "3",
  },
  {
    id: 291,
    word: "overcome",
    meaning: "v.克服",
    synonym: ["defeat"],
    level: "3",
  },
  {
    id: 292,
    word: "overtake",
    meaning: "v.赶上",
    synonym: ["surpass"],
    level: "3",
  },
  {
    id: 293,
    word: "paralyse",
    meaning: "v.使麻痹；使.….瘫痪",
    synonym: ["connot move"],
    level: "3",
  },
  {
    id: 294,
    word: "paramount",
    meaning: "最重要的；主要的",
    synonym: ["principal"],
    level: "3",
  },
  {
    id: 295,
    word: "participate",
    meaning: "v.参加",
    synonym: ["join"],
    level: "3",
  },
  {
    id: 296,
    word: "patient",
    meaning: "adj.有耐性的，能容忍的 n.病人；患者",
    synonym: ["repetitive"],
    level: "3",
  },
  {
    id: 297,
    word: "peak",
    meaning: "n.最局峰，顶点 v.使达到顶峰",
    synonym: ["top"],
    level: "3",
  },
  {
    id: 298,
    word: "permit",
    meaning: "n.许可证；执照 v.许可",
    synonym: ["allow"],
    level: "3",
  },
  {
    id: 299,
    word: "persuade",
    meaning: "v.说服；劝说",
    synonym: ["influence"],
    level: "3",
  },
  {
    id: 300,
    word: "pessimistic",
    meaning: "adj.悲观的",
    synonym: ["negative"],
    level: "3",
  },
  {
    id: 301,
    word: "phase",
    meaning: "n.阶段",
    synonym: ["process"],
    level: "3",
  },
  {
    id: 302,
    word: "physical",
    meaning: "adj.身体上的；物质的",
    synonym: ["body"],
    level: "3",
  },
  {
    id: 303,
    word: "plagiarise",
    meaning: "v.抄袭",
    synonym: ["copy"],
    level: "3",
  },
  {
    id: 304,
    word: "plenty of",
    meaning: "大量的",
    synonym: ["many"],
    level: "3",
  },
  {
    id: 305,
    word: "plot",
    meaning: "v.密谋",
    synonym: ["plan"],
    level: "3",
  },
  {
    id: 306,
    word: "pose",
    meaning: "v.提出；造成；形成",
    synonym: ["cause"],
    level: "3",
  },
  {
    id: 307,
    word: "portable",
    meaning: "adj.便携的",
    synonym: ["conveyable"],
    level: "3",
  },
  {
    id: 308,
    word: "poverty",
    meaning: "n.贫穷",
    synonym: ["poor"],
    level: "3",
  },
  {
    id: 309,
    word: "praise",
    meaning: "v.赞扬",
    synonym: ["commend"],
    level: "3",
  },
  {
    id: 310,
    word: "predict",
    meaning: "v.预测；预知",
    synonym: ["expect"],
    level: "3",
  },
  {
    id: 311,
    word: "pressing",
    meaning: "adj.迫切的",
    synonym: ["urgent"],
    level: "3",
  },
  {
    id: 312,
    word: "private",
    meaning: "adj.私人的；私有的；私下的",
    synonym: ["personal"],
    level: "3",
  },
  {
    id: 313,
    word: "prohibit",
    meaning: "v.禁止",
    synonym: ["not allowed"],
    level: "3",
  },
  {
    id: 314,
    word: "prolong",
    meaning: "v.拉长；延长",
    synonym: ["extend"],
    level: "3",
  },
  {
    id: 315,
    word: "promote",
    meaning: "v.促进；推销",
    synonym: ["improve"],
    level: "3",
  },
  {
    id: 316,
    word: "prosper",
    meaning: "v.使成功；使繁荣",
    synonym: ["success"],
    level: "3",
  },
  {
    id: 317,
    word: "purify",
    meaning: "v.净化",
    synonym: ["clean"],
    level: "3",
  },
  {
    id: 318,
    word: "qualify",
    meaning: "v.取得资格",
    synonym: ["fulfill"],
    level: "3",
  },
  {
    id: 319,
    word: "radical",
    meaning: "adj.彻底的，根本的",
    synonym: ["utmost"],
    level: "3",
  },
  {
    id: 320,
    word: "range",
    meaning: "n.范围；幅度",
    synonym: ["scope"],
    level: "3",
  },
  {
    id: 321,
    word: "rare",
    meaning: "adj.稀有的",
    synonym: ["unusual"],
    level: "3",
  },
  {
    id: 322,
    word: "rate",
    meaning: "n.等级 v.评估",
    synonym: ["rank", "measure"],
    level: "3",
  },
  {
    id: 323,
    word: "react",
    meaning: "v.反应",
    synonym: ["respond"],
    level: "3",
  },
  {
    id: 324,
    word: "recreation",
    meaning: "n.娱乐；消遣",
    synonym: ["entertainment"],
    level: "3",
  },
  {
    id: 325,
    word: "reduction",
    meaning: "n.下降；减少",
    synonym: ["decrease"],
    level: "3",
  },
  {
    id: 326,
    word: "refer to",
    meaning: "指（的是）；涉及；提及",
    synonym: ["talk about"],
    level: "3",
  },
  {
    id: 327,
    word: "rehearsal",
    meaning: "n.排演；预演；练习",
    synonym: ["preparation"],
    level: "3",
  },
  {
    id: 328,
    word: "reject",
    meaning: "v.拒绝；排斥；丢弃",
    synonym: ["exclude"],
    level: "3",
  },
  {
    id: 329,
    word: "relevant",
    meaning: "adj.相关的",
    synonym: ["relative"],
    level: "3",
  },
  {
    id: 330,
    word: "religious",
    meaning: "adj.宗教的；虔诚的",
    synonym: ["sacred"],
    level: "3",
  },
  {
    id: 331,
    word: "reluctant",
    meaning: "adj.不情愿的",
    synonym: ["unwilling"],
    level: "3",
  },
  {
    id: 332,
    word: "reproduce",
    meaning: "v.繁殖",
    synonym: ["breed"],
    level: "3",
  },
  {
    id: 333,
    word: "responsible",
    meaning: "adj.负责的；可靠的；有责任的",
    synonym: ["liable"],
    level: "3",
  },
  {
    id: 334,
    word: "revision",
    meaning: "n.修正",
    synonym: ["editing"],
    level: "3",
  },
  {
    id: 335,
    word: "revive",
    meaning: "v.使复苏；恢复",
    synonym: ["renaissance"],
    level: "3",
  },
  {
    id: 336,
    word: "ruin",
    meaning: "v.毁灭",
    synonym: ["destroy"],
    level: "3",
  },
  {
    id: 337,
    word: "scenic",
    meaning: "adj.风景优美的",
    synonym: ["beautiful"],
    level: "3",
  },
  {
    id: 338,
    word: "shade",
    meaning: "n.遮阳；阴影",
    synonym: ["shelter"],
    level: "3",
  },
  {
    id: 339,
    word: "skepticism",
    meaning: "n.怀疑",
    synonym: ["doubt"],
    level: "3",
  },
  {
    id: 340,
    word: "soar",
    meaning: "v.激增",
    synonym: ["increase"],
    level: "3",
  },
  {
    id: 341,
    word: "solely",
    meaning: "adv.唯一地",
    synonym: ["alone"],
    level: "3",
  },
  {
    id: 342,
    word: "solicitor",
    meaning: "n.律师",
    synonym: ["lawyer"],
    level: "3",
  },
  {
    id: 343,
    word: "steer",
    meaning: "v.控制；引导",
    synonym: ["manage"],
    level: "3",
  },
  {
    id: 344,
    word: "stimulate",
    meaning: "v.刺激；激励",
    synonym: ["motivate"],
    level: "3",
  },
  {
    id: 345,
    word: "stride",
    meaning: "n.进展",
    synonym: ["progress"],
    level: "3",
  },
  {
    id: 346,
    word: "succumb",
    meaning: "vi.屈服",
    synonym: ["yield"],
    level: "3",
  },
  {
    id: 347,
    word: "subdivide",
    meaning: "v.把…….细分",
    synonym: ["break down"],
    level: "3",
  },
  {
    id: 348,
    word: "subtle",
    meaning: "adj.微妙的",
    synonym: ["delicate"],
    level: "3",
  },
  {
    id: 349,
    word: "substance",
    meaning: "n.物质；实质",
    synonym: ["matter"],
    level: "3",
  },
  {
    id: 350,
    word: "sufficiency",
    meaning: "n.足量；充足",
    synonym: ["enough"],
    level: "3",
  },
  {
    id: 351,
    word: "supersede",
    meaning: "v. 取代；代替",
    synonym: ["replace"],
    level: "3",
  },
  {
    id: 352,
    word: "suppress",
    meaning: "v.抑制；隐瞒",
    synonym: ["hold"],
    level: "3",
  },
  {
    id: 353,
    word: "supremacy",
    meaning: "n.至高无上，很高的地位",
    synonym: ["priority"],
    level: "3",
  },
  {
    id: 354,
    word: "suspicious",
    meaning: "adj.可疑的",
    synonym: ["odd"],
    level: "3",
  },
  {
    id: 355,
    word: "sustainable",
    meaning: "adj.可持续的",
    synonym: ["long-term"],
    level: "3",
  },
  {
    id: 356,
    word: "symptom",
    meaning: "n.症状；征兆",
    synonym: ["sign"],
    level: "3",
  },
  {
    id: 357,
    word: "tension",
    meaning: "n.紧张；不安",
    synonym: ["upset"],
    level: "3",
  },
  {
    id: 358,
    word: "term",
    meaning: "n.术语",
    synonym: ["word"],
    level: "3",
  },
  {
    id: 359,
    word: "throughout",
    meaning: "adv.自始至终，到处，全部 prep.贯穿，遍及",
    synonym: ["anywhere"],
    level: "3",
  },
  {
    id: 360,
    word: "toll",
    meaning: "n.通行费 v.征收",
    synonym: ["charge"],
    level: "3",
  },
  {
    id: 361,
    word: "trace",
    meaning: "n.追溯；痕迹",
    synonym: ["track"],
    level: "3",
  },
  {
    id: 362,
    word: "transcend",
    meaning: "v.胜过；超越",
    synonym: ["excel"],
    level: "3",
  },
  {
    id: 363,
    word: "transmit",
    meaning: "v.运输；经过 v.运送",
    synonym: ["send"],
    level: "3",
  },
  {
    id: 364,
    word: "tremendous",
    meaning: "adj.巨大的；惊人的",
    synonym: ["vast"],
    level: "3",
  },
  {
    id: 365,
    word: "trigger",
    meaning: "n.触发；引发，引起",
    synonym: ["begin"],
    level: "3",
  },
  {
    id: 366,
    word: "tropical",
    meaning: "adj.热带的",
    synonym: ["hot"],
    level: "3",
  },
  {
    id: 367,
    word: "unbiased",
    meaning: "adj.公正的；无偏见的",
    synonym: ["fair"],
    level: "3",
  },
  {
    id: 368,
    word: "uniform",
    meaning: "adj.始终如一的",
    synonym: ["consistent"],
    level: "3",
  },
  {
    id: 369,
    word: "valuable",
    meaning: "adj.宝贵的；有价值的",
    synonym: ["benefit"],
    level: "3",
  },
  {
    id: 370,
    word: "versatile",
    meaning: "adj.多功能的",
    synonym: ["all-around"],
    level: "3",
  },
  { id: 371, word: "view", meaning: "v.看", synonym: ["overlook"], level: "3" },
  {
    id: 372,
    word: "violent",
    meaning: "adj.暴力的；猛烈的",
    synonym: ["fierce"],
    level: "3",
  },
  {
    id: 373,
    word: "visible",
    meaning: "adj.明显的；看得见的",
    synonym: ["see"],
    level: "3",
  },
  {
    id: 374,
    word: "visual",
    meaning: "adj.视觉的",
    synonym: ["image"],
    level: "3",
  },
  {
    id: 375,
    word: "well-being",
    meaning: "n.健康；康乐",
    synonym: ["health"],
    level: "3",
  },
];
